[project]
site_name = "nvibrant"
site_description = "🟢 Nvidia Digital Vibrance on Wayland "
site_author = "Tremeschin"
site_url  = "https://nvibrant.tremeschin.com/"
repo_url  = "https://github.com/Tremeschin/nvibrant/"
repo_name = "Tremeschin/nvibrant"
docs_dir  = "website"
nav = [
  {Origin = "https://tremeschin.com"},
  {Home = [
    "index.md",
    "changelog.md",
  ]},
  {Get = [
    "get/index.md",
    {Packages = [
      "get/pypi.md",
      "get/distro.md",
    ]},
    {Origins = [
      "get/source.md",
      "get/actions.md",
    ]},
    {Others = [
      "get/community.md",
    ]},
  ]},
  {Docs = [
    "docs/index.md",
    "docs/vibrance.md",
    "docs/dithering.md",
    "docs/autostart.md",
    "docs/laptop.md",
    "docs/multigpu.md",
  ]},
  {Help = [
    "help.md",
  ]}
]

[project.theme]
name = "zentheme"

[project.theme.icon]
logo = "octicons/chevron-right-16"
tag.default = "material/tag"

[project.extra.tags]
dummy = "key"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Tremeschin"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/KjqvcYwRHm"
