name: Not working in newer drivers?
description: Ask for a patch release here!
title: "[Patch]: New driver v0.0.0"

body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Follow this checklist: https://nvibrant.tremeschin.com/faq/#new-drivers

  - type: input
    id: driver
    attributes:
      label: Driver version (replace on title too)
      description: Output of `cat /sys/module/nvidia/version`
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Linux distribution
      description: Just curious on which rolls drivers first
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Does nvibrant git main local builds..
      options:
        - Compiles and works normally
        - Compiles but fails at runtime
        - Fails to compile (open-gpu related)
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Terminal output
      description: |
        Paste applicable logs showing breaking changes, such as:
        - Files hash to driver version from `uv build` logs
        - Compilation errors related to open-gpu structs
        - No need for the "doesn't bundle" long warning
      render: shell

  - type: textarea
    id: extra
    attributes:
      label: Description
      placeholder: Optional relevant information
