name: release
on:
  workflow_dispatch:

jobs:
  main:
    name: Release
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Get options
        run: uv run nvibrant/version.py >> $GITHUB_ENV

      - name: Compile
        run: uv run nvibrant/build.py

      - name: Build wheel
        run: uv build --wheel

      - name: Publish to PyPI
        run: uv publish dist/*.whl

      - name: Compress binaries
        run: |
          tar --transform='s|^nvibrant/resources/|nvibrant/|' \
              -czf dist/nvibrant-${{env.GHA_VERSION}}-bin.tar.gz \
              nvibrant/resources/*.bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{env.GHA_VERSION}}
          tag_name: v${{env.GHA_VERSION}}
          files: |
            dist/*.whl
            dist/*.tar.gz
